### ISSUE TITLE
HTTP output causes logstash to slow down over time

### ISSUE THREAD

**Issue by jarro2783** [logstash-plugins/logstash-output-http#62]
- Version: Logstash 5.3, logstash-output-http 4.2.0
- Operating System: Ubuntu 16.04
- Config File (if you have sensitive info, please remove it):

We had this in our Puppet code, not sure exactly what it generates to:
```
logstash_indexer::outputs:
  http:
    config:
      endpoint: 'http://127.0.0.1:8500/v1/agent/check/pass/service:beats:1'
    template: 'logstash_shipper/outputs/http.conf.erb'
```

This is the template file:
```
output {
  if [type] == "heartbeat" {
    http {
      http_method => "get"
      url => "<%= @config['endpoint'] %>"
    }
  }
}
```

I posted in https://discuss.elastic.co/t/logstash-slows-down-over-time/81072 that we were having problems with logstash slowing down and failing to process events after a couple of weeks. From this stack dump: https://ptpb.pw/kaxQ, it was determined that the HTTP output was clogging up.

This was particularly strange given that we were barely processing any events through it. We only had one heartbeat event being sent every 10 seconds, compared to several normal log events being processed per second. The `consul` endpoint also showed no delays. The events also seemed to go through without problems, because the `consul` health check never failed, despite the output threads seeming to be busy.

Disabling the HTTP output does seem to have resolved the problem.
